package Day4_Assingments_Exception_checked_unchecked_throw_throws;

public class Parent {
	
	   Parent() throws Exception{
		System.out.println("Inside parent constructor");
		}
	   
		public void fun1(){
		System.out.println("inside fun1 of Parent class");
		}

}
